export interface Country {
  code: string;
  name: string;
  flagPath: string;
}

export const countries: Country[] = [
  { code: "ad", name: "Andorra", flagPath: "/flags/ad.svg" },
  { code: "ae", name: "United Arab Emirates", flagPath: "/flags/ae.svg" },
  { code: "af", name: "Afghanistan", flagPath: "/flags/af.svg" },
  { code: "ag", name: "Antigua and Barbuda", flagPath: "/flags/ag.svg" },
  { code: "ai", name: "Anguilla", flagPath: "/flags/ai.svg" },
  { code: "al", name: "Albania", flagPath: "/flags/al.svg" },
  { code: "am", name: "Armenia", flagPath: "/flags/am.svg" },
  { code: "ao", name: "Angola", flagPath: "/flags/ao.svg" },
  { code: "aq", name: "Antarctica", flagPath: "/flags/aq.svg" },
  { code: "ar", name: "Argentina", flagPath: "/flags/ar.svg" },
  { code: "as", name: "American Samoa", flagPath: "/flags/as.svg" },
  { code: "at", name: "Austria", flagPath: "/flags/at.svg" },
  { code: "au", name: "Australia", flagPath: "/flags/au.svg" },
  { code: "aw", name: "Aruba", flagPath: "/flags/aw.svg" },
  { code: "ax", name: "Åland Islands", flagPath: "/flags/ax.svg" },
  { code: "az", name: "Azerbaijan", flagPath: "/flags/az.svg" },
  { code: "ba", name: "Bosnia and Herzegovina", flagPath: "/flags/ba.svg" },
  { code: "bb", name: "Barbados", flagPath: "/flags/bb.svg" },
  { code: "bd", name: "Bangladesh", flagPath: "/flags/bd.svg" },
  { code: "be", name: "Belgium", flagPath: "/flags/be.svg" },
  { code: "bf", name: "Burkina Faso", flagPath: "/flags/bf.svg" },
  { code: "bg", name: "Bulgaria", flagPath: "/flags/bg.svg" },
  { code: "bh", name: "Bahrain", flagPath: "/flags/bh.svg" },
  { code: "bi", name: "Burundi", flagPath: "/flags/bi.svg" },
  { code: "bj", name: "Benin", flagPath: "/flags/bj.svg" },
  { code: "bl", name: "Saint Barthélemy", flagPath: "/flags/bl.svg" },
  { code: "bm", name: "Bermuda", flagPath: "/flags/bm.svg" },
  { code: "bn", name: "Brunei", flagPath: "/flags/bn.svg" },
  { code: "bo", name: "Bolivia", flagPath: "/flags/bo.svg" },
  { code: "bq", name: "Caribbean Netherlands", flagPath: "/flags/bq.svg" },
  { code: "br", name: "Brazil", flagPath: "/flags/br.svg" },
  { code: "bs", name: "Bahamas", flagPath: "/flags/bs.svg" },
  { code: "bt", name: "Bhutan", flagPath: "/flags/bt.svg" },
  { code: "bv", name: "Bouvet Island", flagPath: "/flags/bv.svg" },
  { code: "bw", name: "Botswana", flagPath: "/flags/bw.svg" },
  { code: "by", name: "Belarus", flagPath: "/flags/by.svg" },
  { code: "bz", name: "Belize", flagPath: "/flags/bz.svg" },
  { code: "ca", name: "Canada", flagPath: "/flags/ca.svg" },
  { code: "cc", name: "Cocos (Keeling) Islands", flagPath: "/flags/cc.svg" },
  { code: "cd", name: "DR Congo", flagPath: "/flags/cd.svg" },
  { code: "cf", name: "Central African Republic", flagPath: "/flags/cf.svg" },
  { code: "cg", name: "Republic of the Congo", flagPath: "/flags/cg.svg" },
  { code: "ch", name: "Switzerland", flagPath: "/flags/ch.svg" },
  { code: "ci", name: "Côte d'Ivoire", flagPath: "/flags/ci.svg" },
  { code: "ck", name: "Cook Islands", flagPath: "/flags/ck.svg" },
  { code: "cl", name: "Chile", flagPath: "/flags/cl.svg" },
  { code: "cm", name: "Cameroon", flagPath: "/flags/cm.svg" },
  { code: "cn", name: "China", flagPath: "/flags/cn.svg" },
  { code: "co", name: "Colombia", flagPath: "/flags/co.svg" },
  { code: "cr", name: "Costa Rica", flagPath: "/flags/cr.svg" },
  { code: "cu", name: "Cuba", flagPath: "/flags/cu.svg" },
  { code: "cv", name: "Cape Verde", flagPath: "/flags/cv.svg" },
  { code: "cw", name: "Curaçao", flagPath: "/flags/cw.svg" },
  { code: "cx", name: "Christmas Island", flagPath: "/flags/cx.svg" },
  { code: "cy", name: "Cyprus", flagPath: "/flags/cy.svg" },
  { code: "cz", name: "Czech Republic", flagPath: "/flags/cz.svg" },
  { code: "de", name: "Germany", flagPath: "/flags/de.svg" },
  { code: "dj", name: "Djibouti", flagPath: "/flags/dj.svg" },
  { code: "dk", name: "Denmark", flagPath: "/flags/dk.svg" },
  { code: "dm", name: "Dominica", flagPath: "/flags/dm.svg" },
  { code: "do", name: "Dominican Republic", flagPath: "/flags/do.svg" },
  { code: "dz", name: "Algeria", flagPath: "/flags/dz.svg" },
  { code: "ec", name: "Ecuador", flagPath: "/flags/ec.svg" },
  { code: "ee", name: "Estonia", flagPath: "/flags/ee.svg" },
  { code: "eg", name: "Egypt", flagPath: "/flags/eg.svg" },
  { code: "eh", name: "Western Sahara", flagPath: "/flags/eh.svg" },
  { code: "er", name: "Eritrea", flagPath: "/flags/er.svg" },
  { code: "es", name: "Spain", flagPath: "/flags/es.svg" },
  { code: "et", name: "Ethiopia", flagPath: "/flags/et.svg" },
  { code: "fi", name: "Finland", flagPath: "/flags/fi.svg" },
  { code: "fj", name: "Fiji", flagPath: "/flags/fj.svg" },
  { code: "fk", name: "Falkland Islands", flagPath: "/flags/fk.svg" },
  { code: "fm", name: "Micronesia", flagPath: "/flags/fm.svg" },
  { code: "fo", name: "Faroe Islands", flagPath: "/flags/fo.svg" },
  { code: "fr", name: "France", flagPath: "/flags/fr.svg" },
  { code: "ga", name: "Gabon", flagPath: "/flags/ga.svg" },
  { code: "gb", name: "United Kingdom", flagPath: "/flags/gb.svg" },
  { code: "gd", name: "Grenada", flagPath: "/flags/gd.svg" },
  { code: "ge", name: "Georgia", flagPath: "/flags/ge.svg" },
  { code: "gf", name: "French Guiana", flagPath: "/flags/gf.svg" },
  { code: "gg", name: "Guernsey", flagPath: "/flags/gg.svg" },
  { code: "gh", name: "Ghana", flagPath: "/flags/gh.svg" },
  { code: "gi", name: "Gibraltar", flagPath: "/flags/gi.svg" },
  { code: "gl", name: "Greenland", flagPath: "/flags/gl.svg" },
  { code: "gm", name: "Gambia", flagPath: "/flags/gm.svg" },
  { code: "gn", name: "Guinea", flagPath: "/flags/gn.svg" },
  { code: "gp", name: "Guadeloupe", flagPath: "/flags/gp.svg" },
  { code: "gq", name: "Equatorial Guinea", flagPath: "/flags/gq.svg" },
  { code: "gr", name: "Greece", flagPath: "/flags/gr.svg" },
  { code: "gs", name: "South Georgia", flagPath: "/flags/gs.svg" },
  { code: "gt", name: "Guatemala", flagPath: "/flags/gt.svg" },
  { code: "gu", name: "Guam", flagPath: "/flags/gu.svg" },
  { code: "gw", name: "Guinea-Bissau", flagPath: "/flags/gw.svg" },
  { code: "gy", name: "Guyana", flagPath: "/flags/gy.svg" },
  { code: "hk", name: "Hong Kong", flagPath: "/flags/hk.svg" },
  { code: "hm", name: "Heard Island and McDonald Islands", flagPath: "/flags/hm.svg" },
  { code: "hn", name: "Honduras", flagPath: "/flags/hn.svg" },
  { code: "hr", name: "Croatia", flagPath: "/flags/hr.svg" },
  { code: "ht", name: "Haiti", flagPath: "/flags/ht.svg" },
  { code: "hu", name: "Hungary", flagPath: "/flags/hu.svg" },
  { code: "id", name: "Indonesia", flagPath: "/flags/id.svg" },
  { code: "ie", name: "Ireland", flagPath: "/flags/ie.svg" },
  { code: "il", name: "Israel", flagPath: "/flags/il.svg" },
  { code: "im", name: "Isle of Man", flagPath: "/flags/im.svg" },
  { code: "in", name: "India", flagPath: "/flags/in.svg" },
  { code: "io", name: "British Indian Ocean Territory", flagPath: "/flags/io.svg" },
  { code: "iq", name: "Iraq", flagPath: "/flags/iq.svg" },
  { code: "ir", name: "Iran", flagPath: "/flags/ir.svg" },
  { code: "is", name: "Iceland", flagPath: "/flags/is.svg" },
  { code: "it", name: "Italy", flagPath: "/flags/it.svg" },
  { code: "je", name: "Jersey", flagPath: "/flags/je.svg" },
  { code: "jm", name: "Jamaica", flagPath: "/flags/jm.svg" },
  { code: "jo", name: "Jordan", flagPath: "/flags/jo.svg" },
  { code: "jp", name: "Japan", flagPath: "/flags/jp.svg" },
  { code: "ke", name: "Kenya", flagPath: "/flags/ke.svg" },
  { code: "kg", name: "Kyrgyzstan", flagPath: "/flags/kg.svg" },
  { code: "kh", name: "Cambodia", flagPath: "/flags/kh.svg" },
  { code: "ki", name: "Kiribati", flagPath: "/flags/ki.svg" },
  { code: "km", name: "Comoros", flagPath: "/flags/km.svg" },
  { code: "kn", name: "Saint Kitts and Nevis", flagPath: "/flags/kn.svg" },
  { code: "kp", name: "North Korea", flagPath: "/flags/kp.svg" },
  { code: "kr", name: "South Korea", flagPath: "/flags/kr.svg" },
  { code: "kw", name: "Kuwait", flagPath: "/flags/kw.svg" },
  { code: "ky", name: "Cayman Islands", flagPath: "/flags/ky.svg" },
  { code: "kz", name: "Kazakhstan", flagPath: "/flags/kz.svg" },
  { code: "la", name: "Laos", flagPath: "/flags/la.svg" },
  { code: "lb", name: "Lebanon", flagPath: "/flags/lb.svg" },
  { code: "lc", name: "Saint Lucia", flagPath: "/flags/lc.svg" },
  { code: "li", name: "Liechtenstein", flagPath: "/flags/li.svg" },
  { code: "lk", name: "Sri Lanka", flagPath: "/flags/lk.svg" },
  { code: "lr", name: "Liberia", flagPath: "/flags/lr.svg" },
  { code: "ls", name: "Lesotho", flagPath: "/flags/ls.svg" },
  { code: "lt", name: "Lithuania", flagPath: "/flags/lt.svg" },
  { code: "lu", name: "Luxembourg", flagPath: "/flags/lu.svg" },
  { code: "lv", name: "Latvia", flagPath: "/flags/lv.svg" },
  { code: "ly", name: "Libya", flagPath: "/flags/ly.svg" },
  { code: "ma", name: "Morocco", flagPath: "/flags/ma.svg" },
  { code: "mc", name: "Monaco", flagPath: "/flags/mc.svg" },
  { code: "md", name: "Moldova", flagPath: "/flags/md.svg" },
  { code: "me", name: "Montenegro", flagPath: "/flags/me.svg" },
  { code: "mf", name: "Saint Martin", flagPath: "/flags/mf.svg" },
  { code: "mg", name: "Madagascar", flagPath: "/flags/mg.svg" },
  { code: "mh", name: "Marshall Islands", flagPath: "/flags/mh.svg" },
  { code: "mk", name: "North Macedonia", flagPath: "/flags/mk.svg" },
  { code: "ml", name: "Mali", flagPath: "/flags/ml.svg" },
  { code: "mm", name: "Myanmar", flagPath: "/flags/mm.svg" },
  { code: "mn", name: "Mongolia", flagPath: "/flags/mn.svg" },
  { code: "mo", name: "Macau", flagPath: "/flags/mo.svg" },
  { code: "mp", name: "Northern Mariana Islands", flagPath: "/flags/mp.svg" },
  { code: "mq", name: "Martinique", flagPath: "/flags/mq.svg" },
  { code: "mr", name: "Mauritania", flagPath: "/flags/mr.svg" },
  { code: "ms", name: "Montserrat", flagPath: "/flags/ms.svg" },
  { code: "mt", name: "Malta", flagPath: "/flags/mt.svg" },
  { code: "mu", name: "Mauritius", flagPath: "/flags/mu.svg" },
  { code: "mv", name: "Maldives", flagPath: "/flags/mv.svg" },
  { code: "mw", name: "Malawi", flagPath: "/flags/mw.svg" },
  { code: "mx", name: "Mexico", flagPath: "/flags/mx.svg" },
  { code: "my", name: "Malaysia", flagPath: "/flags/my.svg" },
  { code: "mz", name: "Mozambique", flagPath: "/flags/mz.svg" },
  { code: "na", name: "Namibia", flagPath: "/flags/na.svg" },
  { code: "nc", name: "New Caledonia", flagPath: "/flags/nc.svg" },
  { code: "ne", name: "Niger", flagPath: "/flags/ne.svg" },
  { code: "nf", name: "Norfolk Island", flagPath: "/flags/nf.svg" },
  { code: "ng", name: "Nigeria", flagPath: "/flags/ng.svg" },
  { code: "ni", name: "Nicaragua", flagPath: "/flags/ni.svg" },
  { code: "nl", name: "Netherlands", flagPath: "/flags/nl.svg" },
  { code: "no", name: "Norway", flagPath: "/flags/no.svg" },
  { code: "np", name: "Nepal", flagPath: "/flags/np.svg" },
  { code: "nr", name: "Nauru", flagPath: "/flags/nr.svg" },
  { code: "nu", name: "Niue", flagPath: "/flags/nu.svg" },
  { code: "nz", name: "New Zealand", flagPath: "/flags/nz.svg" },
  { code: "om", name: "Oman", flagPath: "/flags/om.svg" },
  { code: "pa", name: "Panama", flagPath: "/flags/pa.svg" },
  { code: "pe", name: "Peru", flagPath: "/flags/pe.svg" },
  { code: "pf", name: "French Polynesia", flagPath: "/flags/pf.svg" },
  { code: "pg", name: "Papua New Guinea", flagPath: "/flags/pg.svg" },
  { code: "ph", name: "Philippines", flagPath: "/flags/ph.svg" },
  { code: "pk", name: "Pakistan", flagPath: "/flags/pk.svg" },
  { code: "pl", name: "Poland", flagPath: "/flags/pl.svg" },
  { code: "pm", name: "Saint Pierre and Miquelon", flagPath: "/flags/pm.svg" },
  { code: "pn", name: "Pitcairn Islands", flagPath: "/flags/pn.svg" },
  { code: "pr", name: "Puerto Rico", flagPath: "/flags/pr.svg" },
  { code: "ps", name: "Palestine", flagPath: "/flags/ps.svg" },
  { code: "pt", name: "Portugal", flagPath: "/flags/pt.svg" },
  { code: "pw", name: "Palau", flagPath: "/flags/pw.svg" },
  { code: "py", name: "Paraguay", flagPath: "/flags/py.svg" },
  { code: "qa", name: "Qatar", flagPath: "/flags/qa.svg" },
  { code: "re", name: "Réunion", flagPath: "/flags/re.svg" },
  { code: "ro", name: "Romania", flagPath: "/flags/ro.svg" },
  { code: "rs", name: "Serbia", flagPath: "/flags/rs.svg" },
  { code: "ru", name: "Russia", flagPath: "/flags/ru.svg" },
  { code: "rw", name: "Rwanda", flagPath: "/flags/rw.svg" },
  { code: "sa", name: "Saudi Arabia", flagPath: "/flags/sa.svg" },
  { code: "sb", name: "Solomon Islands", flagPath: "/flags/sb.svg" },
  { code: "sc", name: "Seychelles", flagPath: "/flags/sc.svg" },
  { code: "sd", name: "Sudan", flagPath: "/flags/sd.svg" },
  { code: "se", name: "Sweden", flagPath: "/flags/se.svg" },
  { code: "sg", name: "Singapore", flagPath: "/flags/sg.svg" },
  { code: "sh", name: "Saint Helena", flagPath: "/flags/sh.svg" },
  { code: "si", name: "Slovenia", flagPath: "/flags/si.svg" },
  { code: "sj", name: "Svalbard and Jan Mayen", flagPath: "/flags/sj.svg" },
  { code: "sk", name: "Slovakia", flagPath: "/flags/sk.svg" },
  { code: "sl", name: "Sierra Leone", flagPath: "/flags/sl.svg" },
  { code: "sm", name: "San Marino", flagPath: "/flags/sm.svg" },
  { code: "sn", name: "Senegal", flagPath: "/flags/sn.svg" },
  { code: "so", name: "Somalia", flagPath: "/flags/so.svg" },
  { code: "sr", name: "Suriname", flagPath: "/flags/sr.svg" },
  { code: "ss", name: "South Sudan", flagPath: "/flags/ss.svg" },
  { code: "st", name: "São Tomé and Príncipe", flagPath: "/flags/st.svg" },
  { code: "sv", name: "El Salvador", flagPath: "/flags/sv.svg" },
  { code: "sx", name: "Sint Maarten", flagPath: "/flags/sx.svg" },
  { code: "sy", name: "Syria", flagPath: "/flags/sy.svg" },
  { code: "sz", name: "Eswatini", flagPath: "/flags/sz.svg" },
  { code: "tc", name: "Turks and Caicos Islands", flagPath: "/flags/tc.svg" },
  { code: "td", name: "Chad", flagPath: "/flags/td.svg" },
  { code: "tf", name: "French Southern Territories", flagPath: "/flags/tf.svg" },
  { code: "tg", name: "Togo", flagPath: "/flags/tg.svg" },
  { code: "th", name: "Thailand", flagPath: "/flags/th.svg" },
  { code: "tj", name: "Tajikistan", flagPath: "/flags/tj.svg" },
  { code: "tk", name: "Tokelau", flagPath: "/flags/tk.svg" },
  { code: "tl", name: "Timor-Leste", flagPath: "/flags/tl.svg" },
  { code: "tm", name: "Turkmenistan", flagPath: "/flags/tm.svg" },
  { code: "tn", name: "Tunisia", flagPath: "/flags/tn.svg" },
  { code: "to", name: "Tonga", flagPath: "/flags/to.svg" },
  { code: "tr", name: "Turkey", flagPath: "/flags/tr.svg" },
  { code: "tt", name: "Trinidad and Tobago", flagPath: "/flags/tt.svg" },
  { code: "tv", name: "Tuvalu", flagPath: "/flags/tv.svg" },
  { code: "tw", name: "Taiwan", flagPath: "/flags/tw.svg" },
  { code: "tz", name: "Tanzania", flagPath: "/flags/tz.svg" },
  { code: "ua", name: "Ukraine", flagPath: "/flags/ua.svg" },
  { code: "ug", name: "Uganda", flagPath: "/flags/ug.svg" },
  { code: "um", name: "U.S. Minor Outlying Islands", flagPath: "/flags/um.svg" },
  { code: "us", name: "United States", flagPath: "/flags/us.svg" },
  { code: "uy", name: "Uruguay", flagPath: "/flags/uy.svg" },
  { code: "uz", name: "Uzbekistan", flagPath: "/flags/uz.svg" },
  { code: "va", name: "Vatican City", flagPath: "/flags/va.svg" },
  { code: "vc", name: "Saint Vincent and the Grenadines", flagPath: "/flags/vc.svg" },
  { code: "ve", name: "Venezuela", flagPath: "/flags/ve.svg" },
  { code: "vg", name: "British Virgin Islands", flagPath: "/flags/vg.svg" },
  { code: "vi", name: "U.S. Virgin Islands", flagPath: "/flags/vi.svg" },
  { code: "vn", name: "Vietnam", flagPath: "/flags/vn.svg" },
  { code: "vu", name: "Vanuatu", flagPath: "/flags/vu.svg" },
  { code: "wf", name: "Wallis and Futuna", flagPath: "/flags/wf.svg" },
  { code: "ws", name: "Samoa", flagPath: "/flags/ws.svg" },
  { code: "ye", name: "Yemen", flagPath: "/flags/ye.svg" },
  { code: "yt", name: "Mayotte", flagPath: "/flags/yt.svg" },
  { code: "za", name: "South Africa", flagPath: "/flags/za.svg" },
  { code: "zm", name: "Zambia", flagPath: "/flags/zm.svg" },
  { code: "zw", name: "Zimbabwe", flagPath: "/flags/zw.svg" },
];
